[style.description]
foreground = { rgb = { r = 235, g = 219, b = 178 } }
underline = false
bold = false
italic = false

[style.command_name]
foreground = { rgb = { r = 152, g = 151, b = 26 } }
underline = false
bold = true
italic = false

[style.example_text]
foreground = { rgb = { r = 215, g = 153, b = 33 } }
underline = false
bold = false
italic = false

[style.example_code]
foreground = { rgb = { r = 152, g = 151, b = 26 } }
underline = false
bold = false
italic = false

[style.example_variable]
foreground = { rgb = { r = 104, g = 157, b = 106 } }
underline = false
bold = false
italic = false

[display]
compact = false
use_pager = false

[updates]
auto_update = true
auto_update_interval_hours = 720
archive_source = "https://github.com/tldr-pages/tldr/releases/latest/download/"
